### ISSUE TITLE
Trying to import MF from Py_FS.wrapper.nature_inspired raises ImportError

### ISSUE THREAD

**Issue by aritrartira** [Ritam-Guha/Py_FS#21]
ImportError: cannot import name 'MF' from 'Py_FS.wrapper.nature_inspired' (/usr/local/lib/python3.7/dist-packages/Py_FS/wrapper/nature_inspired/__init__.py)

**Comment by aritrartira** [comment]
The [PyPi page](https://pypi.org/project/Py-FS/) had the filename listed as MF.py instead of MA.py

**Comment by Ritam-Guha** [comment]
Hi,
I am extremely sorry for the inconvenience. Thanks a lot for pointing it out. I think it is just a problem with the readme documentation. We have used the naming 'MA' instead of 'MF' for 'Mayfly Algorithm' 😅. Once again sorry for that. Please let me know if there is any other issue. I have updated the Readme file.

Best,
Ritam
